name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        deno:
          [2.0.0]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Cache images
        id: image-cache
        uses: actions/cache@v2
        with:
          path: |
            _cache
          key: ${{ runner.os }}-img
      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno }}
      - run: deno task build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
